package org.hamciuc.projecteuler.problems;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 * 1: 1
 * 3: 1,3 
 * 6: 1,2,3,6 
 * 10: 1,2,5,10 
 * 15: 1,3,5,15 
 * 21: 1,3,7,21 
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 * 
 * 
 * http://projecteuler.net/problem=12
 * 
 * @author Adrian
 * 
 */

public class Problem12 {
	private static boolean over500Divs(long number) {
		int noDivs = 0;
		for (long i = 1; i < number / 2 + 1; i++) {
			if (number % i == 0) {
				noDivs++;
			}
		}
		return noDivs > 500;
	}

	public static void main(String[] args) {

		long start = 28;
		int count = 7;
		while (!over500Divs(start)) {
			count++;
			start += count;
		}
		System.out.println("Result is " + start);

	}

}
