package org.hamciuc.projecteuler.problems;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * http://projecteuler.net/problem=2
 * 
 * @author Adrian
 * 
 */
public class Problem2 {

	public static void main(String[] args) {
		int sum = 0;
		int prevFib = 1;
		int currentFib = 2;
		while (currentFib <= 4000000) {
			if (currentFib % 2 == 0) {
				sum += currentFib;
			}
			int nextFib = prevFib + currentFib;
			prevFib = currentFib;
			currentFib = nextFib;
		}
		System.out.println("Result is " + sum);
	}

}
